### ISSUE TITLE
API処理中に例外が発生しました

### ISSUE THREAD

**Issue by sherry0757** [sanaehirotaka/logbook-kai#119]
艦これで任務画面を開くとターミナルにログが出ました。

```
WARN  l.i.APIListener [pool-2-thread-3] API処理中に例外が発生しました
javax.json.JsonException: Cannot auto-detect encoding, not enough chars
	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:130)
	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:75)
	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:95)
	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:73)
	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:136)
	at javax.json.Json.createReader(Json.java:225)
	at logbook.internal.APIListener.accept(APIListener.java:69)
	at logbook.internal.proxy.ReverseProxyServlet.lambda$1(ReverseProxyServlet.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

- 航海日誌v19.1.5
- Linux Mint 19 Mate 64bit
- oracle 1.8.0_181

**Comment by sanaehirotaka** [comment]
v19.2.2 で修正しました。
報告ありがとうございました
