### ISSUE TITLE
新海外艦を第一艦隊に入れると、時間表示や現在の戦闘表示に不具合が出る

### ISSUE THREAD

**Issue by manu3da4** [sanaehirotaka/logbook-kai#137]
新海外艦を第一艦隊に入れると、時間表示や現在の戦闘表示に不具合が出る。

コロラド、フレッチャー、ガリバルディのいずれかを第一艦隊に入れると、
・遠征の時間表示が固まる
・入渠の時間表示が固まる
・現在の戦闘表示が固まる
現象が起きています。Win, Mac で起きます。Ubuntuは大丈夫です。
いずれもJDK8を使っています。航海日誌19.5.xからの現象で、19.6.1もです。

**Comment by sanaehirotaka** [comment]
こちらで確認しました(Windows)が現象が再現できませんでした。
そちらの環境で保存されている艦娘の画像データが破損している、ディスク障害で画像が読み込めなくなってしまっている。等の可能性があります。
艦娘の画像データは<logbook-kai/resources/ships>に保存されていますので削除すると改善するかもしれません。

**Comment by manu3da4** [comment]
logbook-kai/resources/ships 以下を消してみましたが変わりませんでした。以下にログの一部を貼ります。これが複数出ます。

2019-06-24 06:27:56,718 ERROR l.i.g.MainController [JavaFX Application Thread] 設定の初期化に失敗しました
java.lang.NullPointerException: null
	at logbook.internal.Ships.airSuperiority(Ships.java:499)
	at java.util.stream.ReferencePipeline$4$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.IntPipeline.reduce(Unknown Source)
	at java.util.stream.IntPipeline.sum(Unknown Source)
	at logbook.internal.gui.FleetTabPane.updateShips(FleetTabPane.java:229)
	at logbook.internal.gui.FleetTabPane.update(FleetTabPane.java:202)
	at logbook.internal.gui.MainController.fleetTab(MainController.java:305)
	at logbook.internal.gui.MainController.checkPort(MainController.java:250)
	at logbook.internal.gui.MainController.update(MainController.java:181)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1105)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$408(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by manu3da4** [comment]
これまで、Chromeで logbook-kai + ubuntu, windows, mac で使っていました。
Win,Macで設定ファイル等をすべて消しても、すぐに固まってしまっていました。
MacでFirefoxと組み合わせたらどうなるだろうかと試してみたところ、問題なく動きました。
その後、Chromeを起動してみたところ、通常通り動くようになりました。
Winの環境でもやってみると、Chromeでは固まっていた状態で、Firefoxにしたところ動き出しました。
その後、Chromeでも動くようになりました。
どうやら、Chromeではなんらかのファイルが作れないor壊れる等の不具合があり、Firefoxではこの不具合が解消し、その後はChromeでも動作するようになるようです。
2ヶ月ぐらいかかりましたが、Chromeとの組み合わせの問題のようです。

**Comment by sanaehirotaka** [comment]
こちらの不具合ですが直接の原因はゲーム開始時に読み込まれる装備や艦娘のデータがうまく取得できていないということまでは判明しているのですが、それがなぜ起こるのかがわかっておらずこちらの環境のChromeでも再現できていません。
Chromeとネット環境の組み合わせによる現象の可能性があり修正が出来ておりません。

**Comment by Sdk0815** [comment]
更新がないようですのでいったん close します。もしまだ問題が継続している場合は別の issue を上げていただけますと助かります。よろしくお願いいたします。
