### ISSUE TITLE
FXMLの初期化に失敗しました

### ISSUE THREAD

**Issue by MikazukiHoshihane** [sanaehirotaka/logbook-kai#2]
sorry,when i want to try use this software and it get this error,why it happened?i ensure the jar file have this fxml.
2016-04-13 20:41:07,138 ERROR l.i.g.MissionPane [JavaFX Application Thread] FXMLの初期化に失敗しました
java.lang.NullPointerException
	at logbook.internal.gui.MissionPane.update(MissionPane.java:109) ~[logbook-kai.jar:?]
	at logbook.internal.gui.MissionPane.initialize(MissionPane.java:69) ~[logbook-kai.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.misc.Trampoline.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.misc.MethodUtil.invoke(Unknown Source) ~[?:1.8.0_77]
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(Unknown Source) ~[jfxrt.jar:?]
	at logbook.internal.gui.MissionPane.<init>(MissionPane.java:60) ~[logbook-kai.jar:?]
and another error is:
2016-04-13 20:41:38,339 ERROR l.i.g.MainController [JavaFX Application Thread] 設定の初期化に失敗しました
java.lang.NullPointerException
	at logbook.internal.gui.MissionPane.update(MissionPane.java:109) ~[logbook-kai.jar:?]
	at logbook.internal.gui.MainController.mission(MainController.java:456) ~[logbook-kai.jar:?]
	at logbook.internal.gui.MainController.checkPort(MainController.java:383) ~[logbook-kai.jar:?]
	at logbook.internal.gui.MainController.update(MainController.java:318) ~[logbook-kai.jar:?]
how can i resolve there errors?(japanese replay is ok)

**Comment by sanaehirotaka** [comment]
遠征の情報が取得出来ていないのが直接の原因ですが、何故取得できないのかが分かりません。
恐らく/kcsapi/api_start2が降って来ていないと思います。

**Comment by MikazukiHoshihane** [comment]
i am use a http proxy to access kancolle,does the reason is my proxy dont send mission information to logbook-kai?but logbook-kai recevied the ndock information........
とりあえず、答えはありがどうございます！

**Comment by sanaehirotaka** [comment]
v0.0.11以降では例外自体は発生しなくなるので一旦閉じます
