### ISSUE TITLE
設定が初期化されてしまう件　他

### ISSUE THREAD

**Issue by toitoi870** [sanaehirotaka/logbook-kai#49]
航海日誌の公開及び更新、いつもありがとうございます

今回、17.8.3にアップデートして以降、以下の問題が発生しています
１．設定が初期化される
２．logbook-kai.jarを（ダブル）クリックしても起動しない

１に関しては、設定を変更しOKボタンを押した後、一度航海日誌を閉じるとその設定が初期化され、もとに戻ってしまいます
また、（おそらく）１に付随して今まで使用していた資材の記録、所有艦娘に関するデータ等が読み込めなくなっています

２に関しでは、クリックでは動作しないため、プログラムから開く→Java(TM)で開いています

公開日誌を使用し始めてからの（主に、資材の）記録が全てなくなってしまうのは少々寂しいものがあります。

参考になるかはわかりませんが、17.8.3にして以降、ログでは以下のような記録が何度も残っています

java.lang.IllegalStateException: PluginContainer not initialized
	at logbook.plugin.PluginContainer.getClassLoader(PluginContainer.java:63) ~[logbook-kai.jar:17.8.3]
	at logbook.plugin.PluginServices.instances(PluginServices.java:23) ~[logbook-kai.jar:17.8.3]
	at logbook.internal.proxy.ProxyHolder.<clinit>(ProxyHolder.java:23) [logbook-kai.jar:17.8.3]
	at logbook.internal.Launcher.exitLocal(Launcher.java:105) [logbook-kai.jar:17.8.3]
	at logbook.internal.Launcher.main(Launcher.java:51) [logbook-kai.jar:17.8.3]

また、これは17.8.3にする以前の最後のログです

2017-08-26 09:14:10,848 WARN l.i.CheckUpdate [Thread-5] アップデートチェックで例外
java.net.UnknownHostException: kancolle.sanaechan.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_131]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[?:1.8.0_131]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_131]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_131]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_131]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_131]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_131]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_131]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_131]
	at logbook.internal.CheckUpdate.run(CheckUpdate.java:36) [logbook-kai.jar:17.8.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-08-26 09:14:10,859 WARN l.i.CheckUpdate [Thread-5] アップデートチェックで例外
java.net.UnknownHostException: kancolle.sanaechan.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:1.8.0_131]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_131]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_131]
	at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_131]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_131]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546) ~[?:1.8.0_131]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[?:1.8.0_131]
	at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_131]
	at logbook.internal.CheckUpdate.run(CheckUpdate.java:36) [logbook-kai.jar:17.8.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

よろしくお願いいたします

**Comment by toitoi870** [comment]
１についての追記です

初期状態での報告書の保存先がC:\Windows\system32になっており、これを遠征報告書.csv等のファイルが存在する場所に変更すると戦闘ログ他を読み込むことはできました
しかし、閉じるとやはり初期状態に戻り、system32が保存先となるため、読み込むことが出来なくなってしまいます

**Comment by Butter-Knife** [comment]
横から失礼します。
自分の使用環境はWindows10 Pro 64bitです。
アップデートしたところ、報告されているような設定が初期化されると言った不具合は起きませんでした。
素人推測ですが、航海日誌に書き込み権限が付与されていないのではないでしょうか？

・logbook-kai.jar のプロパティを開いて「ブロックの解除」チェックボックスをONにする
・航海日誌のzipファイルのプロパティを開いて「ブロックの解除」をチェックしてから改めて上書きする

これで解決しないでしょうか？
Zipファイルの状態でブロック解除すれば、zip内の全てのファイルがブロック解除されますので、自分は毎回後者の操作を行ってからアップデートしています。

**Comment by toitoi870** [comment]
コメントありがとうございます

指摘された手順で行ったところ、問題１が解決しました
また、問題２に関しても上記の手順及び、configフォルダ（とlogsフォルダ）をコピーしないことで解決しました

ありがとうございました

また、開発者のsanaehirotakaさんにも余計な心配をおかけしました
申し訳ありませんでした
